apiVersion: v1
kind: Service
metadata:
  name: superset
  namespace: my-namespace
spec:
  type: NodePort
  selector:
    app: superset
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
      nodePort: 30080
